minimum_pre_commit_version: "2.9.0"
repos:
  - repo: https://github.com/Zac-HD/shed
    rev: 0.10.1
    hooks:
      - id: shed
        # TODO(pcohen): bump to --py310-plus when Talon moves to Python 3.10.
        args: [--refactor, --py39-plus]
        types_or: [python, markdown, rst]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.0"
    hooks:
      - id: prettier
        files: ".*.(md|json|yaml)$"
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.76"
    hooks:
      - id: flynt
